export const ADD_NEW_PRODUCT_START = 'ADD_NEW_PRODUCT_START';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const SET_PRODUCT = 'SET_PRODUCT';
export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';

export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE'
export const SET_EDITED_PRODUCT = 'SET_EDITED_PRODUCT'